name: C/C++ CI

on:
  push:
    branches: [ "prelim" ]
  pull_request:
    branches: [ "prelim" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile lf executable
      run: make

    - name: Run primitives test
      run: ./lf < ./scripts/primitives.f
